global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          service: 'api-gateway'

  - job_name: 'transaction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['transaction-service:8081']
        labels:
          service: 'transaction-service'

  - job_name: 'rule-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rule-engine:8082']
        labels:
          service: 'rule-engine'

  - job_name: 'fraud-decision-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['fraud-decision-engine:8084']
        labels:
          service: 'fraud-decision-engine'

  - job_name: 'explainability-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['explainability-engine:8085']
        labels:
          service: 'explainability-engine'

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8086']
        labels:
          service: 'notification-service'

  - job_name: 'audit-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['audit-service:8087']
        labels:
          service: 'audit-service'

  - job_name: 'ml-engine'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ml-engine:8083']
        labels:
          service: 'ml-engine'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
