apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-config
  namespace: fraud-detection
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: frauddb
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  VAULT_HOST: vault
  VAULT_TOKEN: fraud-root-token
  TRANSACTION_SERVICE_URL: http://transaction-service:8081
  RULE_ENGINE_URL: http://rule-engine:8082
  ML_ENGINE_URL: http://ml-engine:8083
  FRAUD_DECISION_ENGINE_URL: http://fraud-decision-engine:8084
  EXPLAINABILITY_ENGINE_URL: http://explainability-engine:8085
  NOTIFICATION_SERVICE_URL: http://notification-service:8086
  KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/fraud-detection/protocol/openid-connect/certs
---
apiVersion: v1
kind: Secret
metadata:
  name: fraud-db-secret
  namespace: fraud-detection
type: Opaque
stringData:
  DB_USER: frauduser
  DB_PASSWORD: fraudpass
